### ISSUE TITLE
Think about how to pass in a point to add it to the graph

### ISSUE THREAD

**Issue by rowanwins** [rowanwins/visibility-graph#3]
Back in [pyvisgraph](https://github.com/TaipanRex/pyvisgraph) a user can pass in a start or an end point and effectively get it to become part of the graph.

Currently on my demo I'm cheating and just finding the nearest point...

The challenge is that my `createGraphFromGeoJson()` returns the [ngraph](https://github.com/anvaka/ngraph.graph) and you loose all the other info required to add a new point to the graph...

**Comment by dhivehi** [comment]
Any update on this feature?

**Comment by drewjgray** [comment]
Hey @rowanwins have you been able to add this? It would be a super useful addition along with point-in-polygon check for using this library. Thanks for creating this!

**Comment by rowanwins** [comment]
Hi @drewjgray 

Sorry I never got back to it however I'll try and take a look over the next few days. It'll probably mean a slight change to the API but I think it'll be worth it.

For point-in-polygon I recommend another library of mine, [point-in-polygon-hao](https://github.com/rowanwins/point-in-polygon-hao).

Cheers

**Comment by drewjgray** [comment]
That would be amazing @rowanwins, thanks! And thanks for pointing me towards your point-in-polygon library, I will definitely check it out, appreciate it.

**Comment by rowanwins** [comment]
Hi @drewjgray 

I've refactored this and now have this working. I'm just looking at any other API changes I'd like to make before I release the new version.
![screenshot-localhost_8080-2020 04 17-22_53_44](https://user-images.githubusercontent.com/6735870/79571314-58e9fe80-80fe-11ea-8d16-8e3d51f39279.png)

**Comment by drewjgray** [comment]
Amazing! I can't wait to give it a try. Would you be able to share the source of the demo code to easily be able to visualize and test different geojsons?

**Comment by rowanwins** [comment]
@drewjgray PR is available here but probably won't be merged for a while as I do some other investigations.

https://github.com/rowanwins/visibility-graph/pull/5

The `debug` directory shows an example of it in action
https://github.com/rowanwins/visibility-graph/tree/master/debug/src

**Comment by rowanwins** [comment]
Just released 1.0.0 which supports this. See the updated readme
